### ISSUE TITLE
How to get next or previous

### ISSUE THREAD

**Issue by fasteddys** [Smrecz/DecisionTree#1]
Hello, Is there a way to use this as a workflow engineer where the code knows the next or previous state, based on user clicking on a graphviz node?

for e.g. if the mgr wants to reject a leave application in the workflow or approve it... how do we implement that from the UI to the backend and move the application

**Comment by Smrecz** [comment]
Hello @fasteddys, can you get into more detali on the use case?

If your need is to have access to some nodes that are not the trunk then you should implement partial trees and build the full three out of them. This way you'll be able to keep track of "entry points" to the tree (eg. in some dictionary on the side) and start the flow on any given node based on some key parameter.
Key could be a partial tree identifier and node's title at the same time. This way it would be possible to run evaluation starting from any node (knowing it's title). The title could be then coming from UI click but without more details I'm just theoretizing.

**Comment by fasteddys** [comment]
thanks for that answer @Smrecz would be nice to have a sample to follow. 

Going back to your question, to clarify the graphviz seems like a read-only situation, but most use cases, lets say we want to allow a document workflow for a leave application.

in this use case, the manager or the delegated manager, would like to right click and approve (or reject with reason/attach docs). It would be nice to have a pattern or seamless way to have them both (frontend/bkend, deicionTree & Graphviz) work cohesively so we can use this as our simple primary workflow hosted within in asp core.

Perhaps all nodes should have a base class to handle click events coming back from the UI/outside to be state aware to moveNext(), GoBack() etc.

BTW this is good work / extremely useful lib, if it can simplify some of the tree/graph stuff for developers 🥇

**Comment by Smrecz** [comment]
@fasteddys the decision tree is stateless and any behavior changes are done by changing input or mutating the input by node actions.

That being said I think I know what you are after. Looks like it might be a nice feature to add since Graphviz supports generating both [client and server side image maps](https://graphviz.org/docs/outputs/imap/). If there was a way to assign URL to a node this could be leveraged to trigger any action on click by preparing appropriate endpoints.

Would this kind of feature cover your use case? It would allow to basically have a web page with generated graph displayed that would be clickable and each node could be configured with different action URL. 
I must test it to see how it plays out.

**Comment by fasteddys** [comment]
Hello @Smrecz yes, I think that would add nicely, I also found for core cases you decision tree replaces [airflow DAG](https://i.stack.imgur.com/J8vtJ.png) functionality on the .NET side natively. And with Graph Viz, we can let the user trigger the next step, or reject/go back, or defer to some action.

URL action, along with a standard base class to expose some standard things like next previous, branch... so I looked here and was lost by the name [binarynodebuilder](https://github.com/Smrecz/DecisionTree/blob/239ef718448ceccaeb538100c880794cad20369a/DecisionTree/Builders/BinaryDecisionNodeBuilder.cs#L11)

Am I on the right path if I want to expose some of these actions - `such that graphvis can discover, expose to users on rightclick those actions`  for e.g. `Accept ` `Reject ` `Review`, would I add more actions by subclassing this node https://github.com/Smrecz/DecisionTree/blob/239ef718448ceccaeb538100c880794cad20369a/DecisionTree/Builders/BinaryDecisionNodeBuilder.cs#L11

**Comment by Smrecz** [comment]
Hey @fasteddys I'll have some time to look into it this week. My plan is to add optional Uri for each node that can be set up and will generate properly in the DOT definition. 

In case you would like to extend anything you should do it on [nodes ](https://github.com/Smrecz/DecisionTree/blob/239ef718448ceccaeb538100c880794cad20369a/DecisionTree/Decisions/BinaryDecisionNode.cs) themselves, builders are a different thing (kind of a configuration pattern) and they are sealed.

Since the tree is stateless there is no next/previous unless you feed it with some data - what I could expose is a collection of children/parents which is not bad of an idea.
